# Generated by Django 4.1.2 on 2022-11-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=264, unique=True)),
                ('username', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackID', models.CharField(max_length=264, unique=True)),
                ('feedback_content', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewID', models.CharField(max_length=264, unique=True)),
                ('ISBN', models.CharField(max_length=264)),
                ('review_content', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbookID', models.CharField(max_length=264, unique=True)),
                ('ISBN', models.CharField(max_length=264)),
                ('author', models.CharField(max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=29)),
                ('url', models.CharField(max_length=264)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
