# Generated by Django 4.1.2 on 2022-11-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthubapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestID', models.CharField(max_length=264, unique=True)),
                ('requestISBN', models.CharField(max_length=264)),
            ],
        ),
    ]
