# Generated by Django 4.1.2 on 2022-11-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texthubapi', '0002_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='price',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='textbookID',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='url',
        ),
        migrations.AlterField(
            model_name='review',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texthubapi.textbook'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='ISBN',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceID', models.CharField(max_length=264, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=29)),
                ('url', models.CharField(max_length=264)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texthubapi.textbook')),
            ],
        ),
    ]
