# Generated by Django 4.1.2 on 2022-11-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texthubapi', '0003_remove_textbook_price_remove_textbook_textbookid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
